### ISSUE TITLE
password exposed at env.local

### ISSUE THREAD

**Issue by Centurion95** [NicholasHellmers/name-lastname.com#2]
@NicholasHellmers  password exposed at env.local file:

https://github.com/NicholasHellmers/name-lastname.com/blob/master/app/env.local

**Comment by NicholasHellmers** [comment]
Oh, it's a dead env. I have no cluster that uses this URI. Thanks for the catch though!

**Comment by NicholasHellmers** [comment]
Oh, it's a dead env. I have no cluster that uses this URI. Thanks for the catch though!
